apiVersion: v2
name: huaweifusionsolar-exporter
description: Scrape and export huaweisolarfustion metrics
type: application
version: 0.1.4
appVersion: 1.0.0
icon: https://eu5.fusionsolar.huawei.com/pvmswebsite/images/sm/login-logo.png
maintainers:
  - name: NoUseFreak
    email: dries@stenic.io
    url: https://stenic.io
keywords:
  - prometheus
  - huawei
  - fusionsolar
sources:
  - https://github.com/nousefreak/helm-charts
  - https://github.com/nousefreak/huaweifusionsolar-exporter
